-- Create the meet_and_greet_registrations table
create table meet_and_greet_registrations (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  tier text not null,
  state text not null,
  city text,
  preferred_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
